spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/daangn;
    username: sa
    passward:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/
